/**
 * §6.1 compliance, automated.
 *
 * §13 Phase 5 requires "every agent-facing string reviewed against §6.1" and
 * §15 rates the failure Medium-high. A human still reads them once, but this
 * catches regressions at 1:40 when nobody has attention left for prose.
 */
import { test } from 'node:test'
import assert from 'node:assert/strict'
import {
  denialMessage,
  advisoryMessage,
  sequencingMessage,
  semanticConflictMessage,
  noLeaseMessage,
  overflowLine,
  cachedDenialMessage,
  sessionStartContext,
  lintAgentString,
  formatTime,
} from './strings.js'

const clean = (label: string, s: string) => {
  const findings = lintAgentString(s)
  assert.deepEqual(
    findings,
    [],
    `${label} reads as an instruction, not state: ${JSON.stringify(findings)}\n  string: ${s}`,
  )
}

test('the linter catches every "Don\'t write" example from the §6.1 table', () => {
  const bad = [
    'Do not edit this file.',
    'You must claim scope first.',
    'Take task T-07 instead.',
    'Coordinate with Dev before proceeding.',
    'Wait for the type to be defined.',
  ]
  for (const s of bad) {
    assert.ok(lintAgentString(s).length > 0, `linter missed an imperative: ${s}`)
  }
})

test('the linter accepts every "Write instead" example from the §6.1 table', () => {
  const good = [
    'This file is leased by Maya\'s session until 14:32.',
    'No lease exists for this path under your session.',
    'T-07 is open and unassigned.',
    'Dev\'s session is modifying the route this file consumes.',
    'T-01 defines CartItem.variantId and is in progress.',
  ]
  for (const s of good) {
    assert.deepEqual(lintAgentString(s), [], `linter false-positived on: ${s}`)
  }
})

test('denial message is factual and carries the alternatives', () => {
  const s = denialMessage({
    path: 'web/src/components/Cart/CartItem.tsx',
    holderName: 'Maya',
    machine: 'maya-mbp',
    expiresAt: Date.now() + 60_000,
    intent: 'add quantity stepper and wire optimistic update',
    freePaths: ['CartSummary.tsx', 'CartTotals.tsx'],
    openTasks: ['T-07 checkout button loading state'],
  })
  clean('denialMessage', s)
  assert.match(s, /^Switchboard: /)
  assert.match(s, /leased by Maya's session on maya-mbp until \d\d:\d\d/)
  // No guessed pronoun — the hub never learns anyone's pronouns.
  assert.doesNotMatch(s, /\b(?:her|his|hers)\b/i)
  assert.match(s, /currently free: CartSummary\.tsx, CartTotals\.tsx/)
  assert.match(s, /Unassigned open tasks: T-07/)
})

test('denial message degrades gracefully with nothing free and nothing open', () => {
  const s = denialMessage({
    path: 'api/routes/cart.ts',
    holderName: 'Dev',
    machine: 'dev-air',
    expiresAt: Date.now() + 1000,
    intent: '',
    freePaths: [],
    openTasks: [],
  })
  clean('denialMessage (empty)', s)
  assert.match(s, /currently free: none/)
  assert.match(s, /Unassigned open tasks: none/)
})

test('advisory message names the contract and the consumer', () => {
  const s = advisoryMessage({
    path: 'api/routes/cart.ts',
    byName: 'Dev',
    at: Date.now() - 4 * 60_000,
    contractName: 'POST /api/cart/items',
    consumingPath: 'web/src/components/VariantPicker.tsx',
    changeNote: 'The request payload now includes a variantId field.',
  })
  clean('advisoryMessage', s)
  assert.match(s, /4 minutes ago/)
  assert.match(s, /It defines POST \/api\/cart\/items/)
})

test('sequencing, semantic conflict, and the small strings are all factual', () => {
  clean(
    'sequencingMessage',
    sequencingMessage({
      path: 'web/src/components/VariantPicker.tsx',
      blockingTaskId: 'T-01',
      blockingTaskTitle: 'cart route accepts variantId',
      definesWhat: 'CartItem.variantId',
      holderName: 'Dev',
    }),
  )
  clean(
    'semanticConflictMessage',
    semanticConflictMessage({
      otherName: 'Sam',
      otherIntent: 'add loading spinner to add-to-cart',
      reason: 'Both changes drive the same add-to-cart interaction state.',
      sharedConcern: 'the add-to-cart button state',
    }),
  )
  clean('noLeaseMessage', noLeaseMessage('api/types.ts'))
  clean('overflowLine', overflowLine(3))
  clean('cachedDenialMessage', cachedDenialMessage({ path: 'api/types.ts', holderName: 'Maya', ageSec: 90 }))
})

test('overflow line is singular-correct and cheap against the budget', () => {
  assert.match(overflowLine(1), /1 additional notice pending/)
  assert.match(overflowLine(3), /3 additional notices pending/)
  assert.ok(overflowLine(9).length < 200, 'overflow pointer must be tiny')
})

test('session start context is factual and lists the room', () => {
  const s = sessionStartContext({
    humanName: 'Ansh',
    machine: 'ansh-mbp',
    openTasks: [{ id: 'T-07', title: 'checkout button loading state' }],
    activeSessions: [{ humanName: 'Maya', machine: 'maya-mbp', intent: 'quantity stepper' }],
  })
  clean('sessionStartContext', s)
  assert.match(s, /registered as Ansh on ansh-mbp/)
  assert.match(s, /Maya on maya-mbp/)
})

test('session start context handles an empty room', () => {
  const s = sessionStartContext({
    humanName: 'Ansh',
    machine: 'ansh-mbp',
    openTasks: [],
    activeSessions: [],
  })
  clean('sessionStartContext (empty)', s)
  assert.match(s, /No other sessions are active/)
})

test('formatTime is zero-padded 24-hour', () => {
  const d = new Date()
  d.setHours(9, 5, 0, 0)
  assert.equal(formatTime(d.getTime()), '09:05')
  d.setHours(14, 32, 0, 0)
  assert.equal(formatTime(d.getTime()), '14:32')
})
